name: "Smoke test"
inputs:
  template:
    description: "Template to test"
    required: true
  repo-token:
    description: github token
    required: true

runs:
  using: composite
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.repo-token }}

    - name: Checkout main
      id: checkout_release
      uses: actions/checkout@v3

    - name: Build template
      id: build_template
      shell: bash
      run: ${{ github.action_path }}/build.sh ${{ inputs.template }}

    - name: Test template
      id: test_template
      shell: bash
      run: ${{ github.action_path }}/test.sh  ${{ inputs.template }}
